FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN sudo apt-get -y update
RUN sudo apt-get -y install software-properties-common
RUN sudo add-apt-repository -y ppa:bartbes/love-stable
RUN sudo apt-get -y update
RUN sudo apt-get -y install libgtk2.0-0 xdg-utils love